project:
  type: book
  output-dir: "../docs/"

book:
  title: "Visual Statistics"
  author: "Jason Bryer and Bruce Dudek"
  # date: "2024-03-23"
  chapters:
    - index.qmd
    - variance.qmd
    - distributions.qmd
    - correlation.qmd
    - ols_regression.qmd
    - loess.qmd
    - mle.qmd
    - anova.qmd
    - references.qmd
  appendices:
    - calculus.qmd
  repo-url: https://github.com/jbryer/VisualStats/
  repo-subdir: book
  repo-actions: edit

bibliography: references.bib

format:
  html:
    toc: false
    theme: cosmo
    sidebar:
      style: floating
    code-fold: show
    code-summary: "Show the code"
    grid:
      sidebar-width: 200px
      body-width: 1030px
      margin-width: 70px
  # pdf:
  #   documentclass: scrreprt

filters:
  - shinylive

